# -*- coding: utf-8 -*-
"""Pro 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bD5CQUpS4Tg3IpRotNz22RHiuf5Kg40i

Install libraries
"""

!pip install pdfplumber sqlalchemy pyyaml openpyxl

"""Upload Annual Report

"""

from google.colab import files
uploaded = files.upload()
# A button will appear — click it and select your RINL PDF

""" Extract tables from PDF"""

import pdfplumber
import pandas as pd

PDF_PATH = "/content/2024-25.pdf"

def extract_table_from_page(page_number):
    with pdfplumber.open(PDF_PATH) as pdf:
        page = pdf.pages[page_number - 1]
        tables = page.extract_tables()
        return tables

# Extract from all key pages
tables_pl       = extract_table_from_page(18)   # Income Statement
tables_cost     = extract_table_from_page(64)   # Expenditure breakdown
tables_debt     = extract_table_from_page(65)   # Borrowings + Non-current assets
tables_bs       = extract_table_from_page(66)   # Current Assets & Liabilities
tables_summary  = extract_table_from_page(16)   # Financial Highlights

print("✅ Extraction done")
print(f"   Income Statement tables found:  {len(tables_pl)}")
print(f"   Expenditure tables found:       {len(tables_cost)}")
print(f"   Debt tables found:              {len(tables_debt)}")
print(f"   Balance Sheet tables found:     {len(tables_bs)}")
print(f"   Highlights tables found:        {len(tables_summary)}")

""" Preview what was extracted (to verify)

"""

print("=== INCOME STATEMENT (Page 18) ===")
for i, table in enumerate(tables_pl):
    print(f"\nTable {i}:")
    for row in table:
        print(row)

print("\n=== BALANCE SHEET (Page 66) ===")
for i, table in enumerate(tables_bs):
    print(f"\nTable {i}:")
    for row in table:
        print(row)

"""Clean the numbers"""

def clean_number(val):
    """
    Converts Indian accounting format to float:
    '(1,388.62)' → -1388.62   (brackets = negative)
    '18,337.84'  → 18337.84
    '-'          → None
    """
    if not val or str(val).strip() in ['', '-', 'None', 'nan']:
        return None
    val = str(val).replace(',', '').strip()
    if val.startswith('(') and val.endswith(')'):
        val = '-' + val[1:-1]
    try:
        return float(val)
    except:
        return val  # keep as string if it's a label

def table_to_df(table, col_names=None):
    """Converts a raw pdfplumber table to a clean DataFrame"""
    if not table:
        return pd.DataFrame()
    df = pd.DataFrame(table[1:], columns=table[0])  # first row = headers
    df.columns = [str(c).strip() if c else f"col_{i}"
                  for i, c in enumerate(df.columns)]
    return df

print("✅ Cleaning functions ready")

""" Build clean DataFrames"""

# ── Income Statement ──────────────────────────────────────────
df_pl = table_to_df(tables_pl[0])
num_cols = [c for c in df_pl.columns if c != df_pl.columns[0]]
for col in num_cols:
    df_pl[col] = df_pl[col].apply(clean_number)
print("Income Statement:")
print(df_pl)

# ── Expenditure Breakdown ─────────────────────────────────────
df_cost = table_to_df(tables_cost[0])
num_cols = [c for c in df_cost.columns if c != df_cost.columns[0]]
for col in num_cols:
    df_cost[col] = df_cost[col].apply(clean_number)
print("\nExpenditure Breakdown:")
print(df_cost)

# ── Borrowings ────────────────────────────────────────────────
df_debt = table_to_df(tables_debt[0])
num_cols = [c for c in df_debt.columns if c != df_debt.columns[0]]
for col in num_cols:
    df_debt[col] = df_debt[col].apply(clean_number)
print("\nBorrowings:")
print(df_debt)

# ── Balance Sheet (Current Assets & Liabilities) ──────────────
df_bs = table_to_df(tables_bs[0])
num_cols = [c for c in df_bs.columns if c != df_bs.columns[0]]
for col in num_cols:
    df_bs[col] = df_bs[col].apply(clean_number)
print("\nBalance Sheet:")
print(df_bs)

# ── Financial Highlights ──────────────────────────────────────
df_highlights = table_to_df(tables_summary[0])
print("\nFinancial Highlights:")
print(df_highlights)

"""Save as CSV files"""

df_pl.to_csv("/content/clean_income_statement.csv", index=False)
df_cost.to_csv("/content/clean_expenditure.csv", index=False)
df_debt.to_csv("/content/clean_borrowings.csv", index=False)
df_bs.to_csv("/content/clean_balance_sheet.csv", index=False)
df_highlights.to_csv("/content/clean_highlights.csv", index=False)

print("✅ All CSVs saved:")
print("   /content/clean_income_statement.csv")
print("   /content/clean_expenditure.csv")
print("   /content/clean_borrowings.csv")
print("   /content/clean_balance_sheet.csv")
print("   /content/clean_highlights.csv")

""" Load into SQLite database

"""

from sqlalchemy import create_engine

engine = create_engine("sqlite:////content/rinl_financials.db")

df_pl.to_sql("income_statement",   engine, if_exists="replace", index=False)
df_cost.to_sql("expenditure",      engine, if_exists="replace", index=False)
df_debt.to_sql("borrowings",       engine, if_exists="replace", index=False)
df_bs.to_sql("balance_sheet",      engine, if_exists="replace", index=False)
df_highlights.to_sql("highlights", engine, if_exists="replace", index=False)

print("✅ Database created: /content/rinl_financials.db")
print("   Tables loaded: income_statement, expenditure, borrowings, balance_sheet, highlights")

""" Verify everything works

"""

import sqlite3

conn = sqlite3.connect("/content/rinl_financials.db")
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
print("✅ Tables in database:")
for t in tables:
    print(f"   → {t[0]}")

print("\n📊 Income Statement preview:")
df_check = pd.read_sql("SELECT * FROM income_statement", conn)
print(df_check)
conn.close()

"""Download all output files"""

from google.colab import files

files.download("/content/clean_income_statement.csv")
files.download("/content/clean_expenditure.csv")
files.download("/content/clean_borrowings.csv")
files.download("/content/clean_balance_sheet.csv")
files.download("/content/clean_highlights.csv")
files.download("/content/rinl_financials.db")

print("✅ All files downloaded to your computer")